export const ItemData = [
  {
    id: "1",
    fname: "Biren",
    contact: "324234",
    email: "Biren@gmail.com",
    age: "18",
  },
  {
    id: "2",
    fname: "Rikin",
    contact: "3453465",
    email: "Rikin@gmail.com",
    age: "15",
  },
  {
    id: "3",
    fname: "Karan",
    contact: "2343556",
    email: "Karan@gmail.com",
    age: "14",
  },
  {
    id: "4",
    fname: "Arjun",
    contact: "23432",
    email: "Arjun@gmail.com",
    age: "11",
  },
  {
    id: "5",
    fname: "Chirag",
    contact: "88888888",
    email: "Chirag@gmail.com",
    age: "22",
  },
  {
    id: "6",
    fname: "Hardik",
    contact: "44444444",
    email: "Hardik@gmail.com",
    age: "33",
  },
  {
    id: "7",
    fname: "Jenish",
    contact: "3242311",
    email: "Jenish@gmail.com",
    age: "1",
  },
  {
    id: "8",
    fname: "Jignesh",
    contact: "565765",
    email: "Jignesh@gmail.com",
    age: "34",
  },
  {
    id: "9",
    fname: "Piyush",
    contact: "324234",
    email: "Piyush@gmail.com",
    age: "11",
  },
];
